/**
 * Exhibit 2: Ternary Secret Visualizer
 * Shows the constraint: n entries, n/2 are 0, n/4 are +1, n/4 are -1.
 * Animates sampling via Fisher-Yates.
 */

import { sampleTernaryWithSteps, ShuffleStep } from '../crypto/sampling';

export function renderExhibit2(container: HTMLElement): void {
  const demoN = 32; // Manageable size for visualization

  container.innerHTML = `
    <p>S-Cloud+ uses <strong>ternary secrets</strong> with a fixed Hamming weight constraint.
       For dimension <code>n</code>: exactly <code>n/4</code> entries are <code>+1</code>,
       <code>n/4</code> are <code>-1</code>, and <code>n/2</code> are <code>0</code>.
       Total non-zero entries (Hamming weight) = <code>n/2</code>.</p>
    <p>This is generated by populating an array with the exact counts, then applying a
       <strong>Fisher-Yates shuffle</strong> for a uniform random permutation.</p>
    <div class="btn-group">
      <button class="btn" id="ternary-animate">▶ Animate Shuffle (n=${demoN})</button>
      <button class="btn btn-secondary" id="ternary-instant">⟳ Instant Sample</button>
    </div>
    <div id="ternary-stats" class="result-box" style="margin-bottom:1rem"></div>
    <div id="ternary-output"></div>
    <div style="margin-top:1.5rem">
      <h4 style="margin-bottom:0.5rem">Comparison: FrodoKEM vs S-Cloud+ Secret Distribution</h4>
      <div class="result-box">
        <div class="result-row">
          <span class="result-label">FrodoKEM:</span>
          <span>Gaussian distribution over ℤ — entries can be any integer, concentrated near 0.
          Secret coefficients ∈ {-12, …, +12} with χ distribution.</span>
        </div>
        <div class="result-row">
          <span class="result-label">S-Cloud+:</span>
          <span>Ternary {-1, 0, +1} with exact weight constraint.
          Smaller coefficients → faster multiplication. BW₃₂ compensates for reduced entropy.</span>
        </div>
      </div>
    </div>
  `;

  const animateBtn = container.querySelector('#ternary-animate') as HTMLButtonElement;
  const instantBtn = container.querySelector('#ternary-instant') as HTMLButtonElement;
  const output = container.querySelector('#ternary-output') as HTMLElement;
  const stats = container.querySelector('#ternary-stats') as HTMLElement;

  function renderVector(arr: Int16Array, highlightI?: number, highlightJ?: number): string {
    let html = '<div class="vector-display">';
    for (let i = 0; i < arr.length; i++) {
      const val = arr[i];
      const cls = val > 0 ? 'pos' : val < 0 ? 'neg' : 'zero';
      const highlight = (i === highlightI || i === highlightJ)
        ? 'outline:2px solid var(--accent);outline-offset:1px;' : '';
      const label = val > 0 ? '+1' : val < 0 ? '-1' : '0';
      html += `<div class="vec-entry ${cls}" style="${highlight}">${label}</div>`;
    }
    html += '</div>';
    return html;
  }

  function showStats(arr: Int16Array): void {
    let pos = 0, neg = 0, zero = 0;
    for (let i = 0; i < arr.length; i++) {
      if (arr[i] > 0) pos++;
      else if (arr[i] < 0) neg++;
      else zero++;
    }
    stats.innerHTML = `
      <div class="result-row"><span class="result-label">n =</span> <span class="result-value">${arr.length}</span></div>
      <div class="result-row"><span class="result-label">+1 count =</span> <span class="result-value">${pos}</span> (expected n/4 = ${arr.length >> 2})</div>
      <div class="result-row"><span class="result-label">−1 count =</span> <span class="result-value">${neg}</span> (expected n/4 = ${arr.length >> 2})</div>
      <div class="result-row"><span class="result-label">0 count =</span> <span class="result-value">${zero}</span> (expected n/2 = ${arr.length >> 1})</div>
      <div class="result-row"><span class="result-label">Hamming weight =</span> <span class="result-value">${pos + neg}</span> (expected n/2 = ${arr.length >> 1})</div>
    `;
  }

  function instantSample(): void {
    const { result } = sampleTernaryWithSteps(demoN);
    output.innerHTML = renderVector(result);
    showStats(result);
  }

  async function animateSample(): Promise<void> {
    animateBtn.disabled = true;
    instantBtn.disabled = true;

    const { steps } = sampleTernaryWithSteps(demoN);

    // Show initial state
    output.innerHTML = renderVector(steps[0].array);
    showStats(steps[0].array);

    // Animate through a subset of steps (too many would be too slow)
    const stepInterval = Math.max(1, Math.floor(steps.length / 40));
    for (let k = 1; k < steps.length; k += stepInterval) {
      const step = steps[k];
      output.innerHTML = renderVector(step.array, step.i, step.j);
      showStats(step.array);
      await sleep(80);
    }

    // Show final
    const final = steps[steps.length - 1];
    output.innerHTML = renderVector(final.array);
    showStats(final.array);

    animateBtn.disabled = false;
    instantBtn.disabled = false;
  }

  animateBtn.addEventListener('click', animateSample);
  instantBtn.addEventListener('click', instantSample);
  instantSample();
}

function sleep(ms: number): Promise<void> {
  return new Promise(resolve => setTimeout(resolve, ms));
}
